import { index, integer, sqliteTable, text } from 'drizzle-orm/sqlite-core';
import { relations } from 'drizzle-orm';
import { nanoid } from 'nanoid';
import { createInsertSchema, createSelectSchema, createUpdateSchema } from 'drizzle-zod';
import { z } from 'zod';

import { timestamps, createdAt } from '$lib/server/db/helpers';
import { user } from '$lib/server/modules/auth/auth.drizzle';
import { productVariant } from '$lib/server/modules/catalog/product/product-variant.drizzle';
import { coupon } from '$lib/server/modules/commerce/coupon/coupon.drizzle';

// ── Constants ──────────────────────────────────────────────────────────────

export const ORDER_STATUSES = [
	'pending', // just placed, awaiting confirmation
	'confirmed', // admin confirmed, payment valid
	'processing', // being packed
	'shipped', // handed to delivery service
	'delivered', // customer received
	'cancelled', // cancelled by customer or admin
	'refunded' // refund issued
] as const;

export const ORDER_PAYMENT_STATUSES = [
	'pending',
	'paid',
	'failed',
	'refunded',
	'partially_refunded'
] as const;

export const PAYMENT_METHODS = ['cod', 'payhere', 'bank_transfer'] as const;

export type OrderStatus = (typeof ORDER_STATUSES)[number];
export type PaymentStatus = (typeof ORDER_PAYMENT_STATUSES)[number];
export type PaymentMethod = (typeof PAYMENT_METHODS)[number];

// ── order ──────────────────────────────────────────────────────────────────

export const order = sqliteTable(
	'order',
	{
		id: text('id')
			.primaryKey()
			.$defaultFn(() => nanoid()),

		/**
		 * Human-readable reference shown on invoices and in emails.
		 * Format: CC-YYYY-NNNNN  (generated by service layer).
		 */
		orderNumber: text('order_number').notNull().unique(),

		/** Null for guest checkouts. */
		userId: text('user_id').references(() => user.id, { onDelete: 'set null' }),

		// ── Shipping address snapshot ──────────────────────────────────────
		// Snapshotted so historical orders are unaffected when the customer
		// edits their saved address later.

		shippingFirstName: text('shipping_first_name').notNull(),
		shippingLastName: text('shipping_last_name').notNull(),
		shippingPhone: text('shipping_phone').notNull(),
		shippingEmail: text('shipping_email').notNull(),
		shippingAddressLine1: text('shipping_address_line_1').notNull(),
		shippingAddressLine2: text('shipping_address_line_2'),
		shippingCity: text('shipping_city').notNull(),
		shippingDistrict: text('shipping_district').notNull(),
		shippingPostalCode: text('shipping_postal_code'),
		shippingCountry: text('shipping_country').default('LK').notNull(),

		// ── Status ────────────────────────────────────────────────────────
		status: text('status', { enum: ORDER_STATUSES }).default('pending').notNull(),
		paymentStatus: text('payment_status', { enum: ORDER_PAYMENT_STATUSES })
			.default('pending')
			.notNull(),
		paymentMethod: text('payment_method', { enum: PAYMENT_METHODS }).notNull(),

		// ── Financials (all in LKR cents) ─────────────────────────────────
		subtotal: integer('subtotal').notNull(),
		discountAmount: integer('discount_amount').default(0).notNull(),
		shippingAmount: integer('shipping_amount').default(0).notNull(),
		total: integer('total').notNull(),

		// ── Coupon snapshot ───────────────────────────────────────────────
		couponId: text('coupon_id').references(() => coupon.id, { onDelete: 'set null' }),
		/** Stored separately so it remains legible even if the coupon is deleted. */
		couponCode: text('coupon_code'),

		// ── Notes ─────────────────────────────────────────────────────────
		/** Optional delivery instructions from the customer. */
		notes: text('notes'),
		/** Internal notes visible only to admin. */
		adminNotes: text('admin_notes'),

		// ── Delivery tracking ─────────────────────────────────────────────
		/** e.g. "Kapruka", "PickMe Delivery", "DHL" */
		deliveryServiceName: text('delivery_service_name'),
		trackingNumber: text('tracking_number'),
		trackingUrl: text('tracking_url'),
		shippedAt: integer('shipped_at', { mode: 'timestamp_ms' }),
		deliveredAt: integer('delivered_at', { mode: 'timestamp_ms' }),

		// ── Bank transfer ─────────────────────────────────────────────────
		/** Reference / slip number provided by customer for bank transfer orders. */
		bankTransferReference: text('bank_transfer_reference'),

		// ── Cancellation ──────────────────────────────────────────────────
		cancelledAt: integer('cancelled_at', { mode: 'timestamp_ms' }),
		cancellationReason: text('cancellation_reason'),

		...timestamps
	},
	(table) => [
		index('order_user_idx').on(table.userId),
		index('order_status_idx').on(table.status),
		index('order_payment_status_idx').on(table.paymentStatus),
		index('order_number_idx').on(table.orderNumber),
		index('order_created_at_idx').on(table.createdAt)
	]
);

// ── order_item ─────────────────────────────────────────────────────────────

export const orderItem = sqliteTable(
	'order_item',
	{
		id: text('id')
			.primaryKey()
			.$defaultFn(() => nanoid()),

		orderId: text('order_id')
			.notNull()
			.references(() => order.id, { onDelete: 'cascade' }),

		/**
		 * Nullable FK — if a variant is later deleted the line item is kept
		 * intact via the snapshots below.
		 */
		variantId: text('variant_id').references(() => productVariant.id, {
			onDelete: 'set null'
		}),

		// ── Product snapshots ──────────────────────────────────────────────
		// Ensure orders remain accurate regardless of future catalogue changes.
		productName: text('product_name').notNull(),
		productSlug: text('product_slug').notNull(),
		variantSku: text('variant_sku').notNull(),
		variantSize: text('variant_size'),
		variantColor: text('variant_color'),
		/** R2 key of the product image at order time. */
		imageR2Key: text('image_r2_key'),

		quantity: integer('quantity').notNull(),

		/** Price per unit in LKR cents at checkout time. */
		unitPrice: integer('unit_price').notNull(),

		/** unitPrice × quantity. */
		totalPrice: integer('total_price').notNull(),

		...createdAt
	},
	(table) => [index('order_item_order_idx').on(table.orderId)]
);

// ── Relations ──────────────────────────────────────────────────────────────
// The many-sides (payments, couponUsages) are defined in db/relations.ts
// to avoid circular imports with payment.drizzle.ts and coupon-usage.drizzle.ts.

export const orderRelations = relations(order, ({ one, many }) => ({
	user: one(user, {
		fields: [order.userId],
		references: [user.id]
	}),
	coupon: one(coupon, {
		fields: [order.couponId],
		references: [coupon.id]
	}),
	items: many(orderItem)
}));

export const orderItemRelations = relations(orderItem, ({ one }) => ({
	order: one(order, {
		fields: [orderItem.orderId],
		references: [order.id]
	}),
	variant: one(productVariant, {
		fields: [orderItem.variantId],
		references: [productVariant.id]
	})
}));

// ── Zod schemas ────────────────────────────────────────────────────────────

export const insertOrderSchema = createInsertSchema(order, {
	shippingEmail: (s) => s.email(),
	shippingPhone: (s) => s.regex(/^\+?[0-9\s\-()]{7,20}$/),
	subtotal: (s) => s.min(0),
	total: (s) => s.min(0)
}).omit({ id: true });

export const selectOrderSchema = createSelectSchema(order);
export const updateOrderSchema = createUpdateSchema(order).omit({ id: true });

export const insertOrderItemSchema = createInsertSchema(orderItem, {
	quantity: (s) => s.min(1),
	unitPrice: (s) => s.min(0),
	totalPrice: (s) => s.min(0)
}).omit({ id: true });

export const selectOrderItemSchema = createSelectSchema(orderItem);

// ── Types ──────────────────────────────────────────────────────────────────

export type Order = z.infer<typeof selectOrderSchema>;
export type InsertOrder = z.infer<typeof insertOrderSchema>;
export type UpdateOrder = z.infer<typeof updateOrderSchema>;

export type OrderItem = z.infer<typeof selectOrderItemSchema>;
export type InsertOrderItem = z.infer<typeof insertOrderItemSchema>;
